### ISSUE TITLE
Package it in Docker / `docker-compose.yml`

### ISSUE THREAD

**Issue by GamePlayer-8** [signag/raspi-cam-srv#40]
Hello,

Any way that the project would have a `docker-compose.yml` for easy deployment?

**Comment by signag** [comment]
Hi, 
thanks for this suggestion.

This is on my ToDo list since long.

**Comment by GamePlayer-8** [comment]
Heya,

Have you tried adding:
```
    shm_size: '1gb'
    deploy:
      resources:
        limits:
          memory: '2g' # with zram if not enough memory
```

and see how it goes?

Also is `dmesg` printing anything special?
